[package]
org = "user"
name = "CarRentalSystem_Client"
version = "0.1.0"
distribution = "2201.10.0"

[dependencies]
"ballerina/grpc" = "1.12.3"
"ballerina/io" = "1.6.3"
"ballerina/protobuf" = "1.6.1"

[build-options]
observabilityIncluded = true
